{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "temporal-operator.fullname" . }}-metrics
  {{- if .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: temporal-operator
  {{- include "temporal-operator.labels" . | nindent 4 }}
  {{- with .Values.metrics.serviceMonitor.additionalLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - port: metrics
    path: /metrics
    {{- with .Values.metrics.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
    {{- include "temporal-operator.selectorLabels" . | nindent 6 }}
{{- end }}
